/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSpringvoxPbxRouteImport } from './routes/solutions/springvox-pbx'
import { Route as SolutionsSpringvoxConnectRouteImport } from './routes/solutions/springvox-connect'
import { Route as SolutionsRekallIqRouteImport } from './routes/solutions/rekall-iq'
import { Route as SolutionsIdsCybersecurityRouteImport } from './routes/solutions/ids-cybersecurity'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSpringvoxPbxRoute = SolutionsSpringvoxPbxRouteImport.update({
  id: '/springvox-pbx',
  path: '/springvox-pbx',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSpringvoxConnectRoute =
  SolutionsSpringvoxConnectRouteImport.update({
    id: '/springvox-connect',
    path: '/springvox-connect',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsRekallIqRoute = SolutionsRekallIqRouteImport.update({
  id: '/rekall-iq',
  path: '/rekall-iq',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsIdsCybersecurityRoute =
  SolutionsIdsCybersecurityRouteImport.update({
    id: '/ids-cybersecurity',
    path: '/ids-cybersecurity',
    getParentRoute: () => SolutionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/ids-cybersecurity': typeof SolutionsIdsCybersecurityRoute
  '/solutions/rekall-iq': typeof SolutionsRekallIqRoute
  '/solutions/springvox-connect': typeof SolutionsSpringvoxConnectRoute
  '/solutions/springvox-pbx': typeof SolutionsSpringvoxPbxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/ids-cybersecurity': typeof SolutionsIdsCybersecurityRoute
  '/solutions/rekall-iq': typeof SolutionsRekallIqRoute
  '/solutions/springvox-connect': typeof SolutionsSpringvoxConnectRoute
  '/solutions/springvox-pbx': typeof SolutionsSpringvoxPbxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/ids-cybersecurity': typeof SolutionsIdsCybersecurityRoute
  '/solutions/rekall-iq': typeof SolutionsRekallIqRoute
  '/solutions/springvox-connect': typeof SolutionsSpringvoxConnectRoute
  '/solutions/springvox-pbx': typeof SolutionsSpringvoxPbxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/services'
    | '/solutions'
    | '/solutions/ids-cybersecurity'
    | '/solutions/rekall-iq'
    | '/solutions/springvox-connect'
    | '/solutions/springvox-pbx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/services'
    | '/solutions'
    | '/solutions/ids-cybersecurity'
    | '/solutions/rekall-iq'
    | '/solutions/springvox-connect'
    | '/solutions/springvox-pbx'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/services'
    | '/solutions'
    | '/solutions/ids-cybersecurity'
    | '/solutions/rekall-iq'
    | '/solutions/springvox-connect'
    | '/solutions/springvox-pbx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/springvox-pbx': {
      id: '/solutions/springvox-pbx'
      path: '/springvox-pbx'
      fullPath: '/solutions/springvox-pbx'
      preLoaderRoute: typeof SolutionsSpringvoxPbxRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/springvox-connect': {
      id: '/solutions/springvox-connect'
      path: '/springvox-connect'
      fullPath: '/solutions/springvox-connect'
      preLoaderRoute: typeof SolutionsSpringvoxConnectRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/rekall-iq': {
      id: '/solutions/rekall-iq'
      path: '/rekall-iq'
      fullPath: '/solutions/rekall-iq'
      preLoaderRoute: typeof SolutionsRekallIqRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/ids-cybersecurity': {
      id: '/solutions/ids-cybersecurity'
      path: '/ids-cybersecurity'
      fullPath: '/solutions/ids-cybersecurity'
      preLoaderRoute: typeof SolutionsIdsCybersecurityRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsIdsCybersecurityRoute: typeof SolutionsIdsCybersecurityRoute
  SolutionsRekallIqRoute: typeof SolutionsRekallIqRoute
  SolutionsSpringvoxConnectRoute: typeof SolutionsSpringvoxConnectRoute
  SolutionsSpringvoxPbxRoute: typeof SolutionsSpringvoxPbxRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsIdsCybersecurityRoute: SolutionsIdsCybersecurityRoute,
  SolutionsRekallIqRoute: SolutionsRekallIqRoute,
  SolutionsSpringvoxConnectRoute: SolutionsSpringvoxConnectRoute,
  SolutionsSpringvoxPbxRoute: SolutionsSpringvoxPbxRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
